removeOldFiles:
    c_drive:
        c_downloads:
            path: "c:/downloads"
            extensions: "err,log,out"
            age: 2

removeOldFilesSchedule:
  days: 'MON,TUE,WED,THU,FRI'
  time: '12:00'
  taskname: 'remove_old_files'
