removeOldFiles:
    c_drive:
        c_downloads:
            move_only: "c:/downloads/archived"
            path: "c:/downloads"
            extensions: "err,log,out"
            age: 2
        c_temp:
              move_only: ""
              path: "c:/temp"
              extensions: "err,log,out"
              dirpatterns: ""
              age: 2

removeOldFilesSchedule:
  days: 'MON,TUE,WED,THU,FRI'
  time: '12:00'
  taskname: 'remove_old_files'
